### ISSUE TITLE
Daphne

### ISSUE THREAD

**Issue by vince87** [PietDAmore/240p-Theme#1]
Hello, your theme is fantastic!
In my JammaPi works beautifully!
Is possible to add Daphne menu?
Thanks in advice
Vincenzo

**Comment by PietDAmore** [comment]
Hi Vincenzo,

thank you for reaching out. I don't have so much experience with Daphne but will this device here fit in? http://www.emu-france.com/emulateurs/6-arcades/309-laserdisc-video-games/ or should I use the Daphne logo?

Best,
Piet

**Comment by vince87** [comment]
Hi Piet,
thanks for the answer, yes, the Daphne is the laser disk emulator.
I think that as a logo, you can use that Daphne or maybe dragon lair or space ace that are the best known!
Thanks
Vincenzo

**Comment by PietDAmore** [comment]
Alright, check the update - tell me if it works!

**Comment by vince87** [comment]
Perfect, Dirk was a good choice!
